# themes
[
  # "AbyssGreen"
  # "Abyssal-Wave"
  # "Amethyst-Aura"
  # "AncientAliens"
  # "Another-World"
  # "Bad-Blood"
  # "BlueSky"
  # "Cat-Latte"
  "Catppuccin-Latte"
  "Catppuccin-Mocha"
  # "Code-Garden"
  # "Cosmic-Blue"
  # "Crimson-Blade"
  # "Crimson-Blue"
  "Decay-Green"
  # "DoomBringers"
  # "Dracula"
  "Edge-Runner"
  # "Electra"
  # "Eternal-Arctic"
  # "Ever-Blushing"
  "Frosted-Glass"
  "Graphite-Mono"
  # "Green-Lush"
  # "Greenify"
  # "Grukai"
  "Gruvbox-Retro"
  # "Hack-the-Box"
  # "Ice-Age"
  # "LimeFrenzy"
  # "Mac-OS"
  "Material-Sakura"
  # "Monokai"
  # "Monterey-Frost"
  # "Moonlight"
  # "Nightbrew"
  "Nordic-Blue"
  "Obsidian-Purple"
  # "One-Dark"
  # "Oxo-Carbon"
  # "Paranoid-Sweet"
  # "Piece-Of-Mind"
  # "Pixel-Dream"
  # "Rain-Dark"
  # "Red-Stone"
  "Rose-Pine"
  # "Scarlet-Night"
  # "Sci-fi"
  # "Solarized-Dark"
  "Synth-Wave"
  "Tokyo-Night"
  # "Tundra"
  # "Vanta-Black"
  # "Windows-11"
]

# https://github.com/richen604/hydenix/tree/main/hydenix/sources/themes
